### ISSUE TITLE
Cannot render template

### ISSUE THREAD

**Issue by earllapura** [chadicus/slim-oauth2#4]
I integrated your implementation into my system and I cannot render the authorization template form. The error message and trace is as follows:

Details
Type: RuntimeException
Message: View cannot render `authorize.phtml` because the template does not exist
File: `C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\View.php`
Line: 272

Trace

```
#0 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\View.php(255): Slim\View->render('authorize.phtml', NULL)
#1 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\View.php(243): Slim\View->fetch('authorize.phtml', NULL)
#2 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Slim.php(757): Slim\View->display('authorize.phtml')
#3 C:\xampp\htdocs\api-fmis\v2\vendor\chadicus\slim-oauth2-routes\src\Authorize.php(65): Slim\Slim->render('authorize.phtml', Array)
#4 [internal function]: Chadicus\Slim\OAuth2\Routes\Authorize->__invoke()
#5 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Route.php(468): call_user_func_array(Object(Chadicus\Slim\OAuth2\Routes\Authorize), Array)
#6 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Slim.php(1357): Slim\Route->dispatch()
#7 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Middleware\Flash.php(85): Slim\Slim->call()
#8 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Middleware\MethodOverride.php(92): Slim\Middleware\Flash->call()
#9 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Middleware\PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#10 C:\xampp\htdocs\api-fmis\v2\vendor\slim\slim\Slim\Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#11 C:\xampp\htdocs\api-fmis\v2\index.php(14183): Slim\Slim->run()
#12 {main}
```

**Comment by earllapura** [comment]
Oh I forgot to change the Slim template directory path in the config.
